### PR TITLE
Fixing bad commit, cleaning CHAMP density processing.

### PR DESCRIPTION
**Pull request by timhoar**
George ... I've spent a little time cleaning up a problem I guess I created in November. I do not belive this will directly impact you (are you intending to use CHAMP observations?) but these messes need to be cleaned up for my sanity.

Let me know if you have any trouble with them.

### CODE REVIEW

**Comment by gwbowden** [comment]
Thanks Tim. I was using the CHAMP observation converter yesterday (having resolved the relevant conflicted regions in the version on Gadi). This was part of a final (4 member) ensemble test to make sure the assimilation ran through the entire period while evaluating SAT_RHO as well as assimilating the GOLD data. DART was working but TIE-GCM encountered a Kp value outside the range it could handle 99 hours into the assimilation period. Once that problem is fixed, I'll run the experiment with 60 ensemble members and let you know how that goes.

**Comment by timhoar** [comment]
George, with a four member ensemble the regression is pretty unreliable and
could possibly cause bad values to be part of the update. A 60 member
ensemble would surely provide a more robust regression and you may not have
the parameter problems.

Tim

On Jan 19, 2021, at 5:20 PM, George <notifications@github.com> wrote:

﻿

Thanks Tim. I was using the CHAMP observation converter yesterday (having
resolved the relevant conflicted regions in the version on Gadi). This was
part of a final (4 member) ensemble test to make sure the assimilation ran
through the entire period while evaluating SAT_RHO as well as assimilating
the GOLD data. DART was working but TIE-GCM encountered a Kp value outside
the range it could handle 99 hours into the assimilation period. Once that
problem is fixed, I'll run the experiment with 60 ensemble members and let
you know how that goes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gwbowden/DART/pull/3#issuecomment-763236536>, or
unsubscribe

**Comment by gwbowden** [comment]
The 4 member ensemble did show some unusual behaviour during the assimilation. Large regions with negative temperatures in the posterior developed several times, near where observations were taken. This didn't crash the code because the quantity wasn't copied back. Hopefully this behaviour will improve with the 60 member ensemble. The actual error which crashed the code came when TIEGCM read a value of the geomagnetic index Kp > 9 (the maximum on that scale) from the perturbed space weather index file.

**Comment by gwbowden** [comment]
Actually running for a 60 member ensemble is giving me:
`calling model advance now:`
`Starting advance_model for process 0 at Wed Jan 20 17:28:00 AEDT 2021`
`tiegcm.nml updated with new start/stop time for ensemble member 1`
`renamed 'tiegcm.nml' -> 'tiegcm.nml.original'`
`renamed 'tiegcm.nml.updated' -> 'tiegcm.nml'`
`grep: log_advance.0001.txt: Stale file handle`
`ERROR: tiegcm model advance failed.`
`ERROR: check advance_temp0000/log_advance.0001.txt`
At which point the execution ceases. This seems to cut TIEGCM off mid-run without generating an error message in `advance_temp0000/log_advance.0001.txt`. Is this problem recognisable?

**Comment by timhoar** [comment]
A 'stale file handle' usually means the file doesn't exist anymore ... like
the directory it was in was removed.
The 60 member ensemble will take a lot longer to advance (15x) than the 4
member case since each model state is updated in turn. Did you provide
enough time for the job to finish?
Was it the first model advance or ????

Tim Hoar
Data Assimilation Research Section
National Center for Atmospheric Research
thoar@ucar.edu
303.497.1708

*As of 3/17/20, NCAR is on mandatory telework.*
*Please reach me via email or Google Chat/Meet instead of my office phone.*

**Comment by gwbowden** [comment]
It was the first advance for the first ensemble member, running with 40:00:00 walltime requested. I had changed `num_output_state_members` and `num_output_obs_members` to 1, thinking this would only affect the diagnostic files. Strangely, the code is now running (currently advancing ensemble members to the first assimilation time) having set those variables back to 4.

**Comment by timhoar** [comment]
Ugh ... your intuition was correct that changing num_output_state_members
 and num_output_obs_members to 1 should only affect the diagnostic files. I
will suggest that in your case, num_output_obs_members should always be the
ensemble size - this will allow you to explore the impact of the
assimilation with a rank histogram and will only impact the size of the
obs_seq.final file - which is pretty minimal in your case.

I know of no reason why having the num_output_state_members equal to 4
(rather than 1) would cause the job to run. I am almost certain that the
problem was with the node(s) rather than the code.

I am working with people using GITM on a remote machine (as well as a few
others) and am getting muddled about the nuances of the machines, several
of them have just apocryphal filesystem performance.
If gadi is one of them ... you might want to read
https://news.sherlock.stanford.edu/posts/when-setting-an-environment-variable-gives-you-a-40-x-speedup
and then

$ export LS_COLORS='ex=00:su=00:sg=00:ca=00:'$ ls --color=always

If a simple resubmission of the same job completes, I would contact your
system accounting people to recover whatever 'currency' was charged to your
account.
On large machines, it is not terribly uncommon to get dispatched on 'bad'
nodes. Jobs fail on bad nodes, those nodes become available, and the next
job gets dispatched on the available nodes ... unless there is a very
sophisticated back end to the queueing system to detect how often and
perhaps why jobs fail on nodes. That's a hard thing to do, and I do not
belive it can be done perfectly as jobs do fail for user-related reasons.


Tim Hoar
Data Assimilation Research Section
National Center for Atmospheric Research
thoar@ucar.edu
303.497.1708

*As of 3/17/20, NCAR is on mandatory telework.*
*Please reach me via email or Google Chat/Meet instead of my office phone.*

**Comment by gwbowden** [comment]
Still trying to work through some issues. I'm finding that setting num_output_obs_members to 60 causes the program to fail due to lack of memory, even after providing the maximum available for a standard Gadi node. Otherwise, there seems to be a problem that's causing the TIEGCM advance to fail for some ensemble members after 22 steps. TIEGCM seems to be unable to find a maximum NE for some vertical profiles, which precedes a segmentation fault. Is it possible that the assimilation is driving ensemble members into pathological states without an NE peak? If so, is there some way telling the algorithm not to do that?

**Comment by timhoar** [comment]
Setting num_output_obs_members to the ensemble size (60 in this case) would be a most unexpected failure. I posit that you might still benefit from using fewer CPUS/tasks while still using the whole node. I am not privvy to the details of the queues on gadi, nor how the PBS is configured such that you can request a whole node but only use a subset of the CPUS. Apparently your problem is memory-limited and the solution is to give each task more memory.  Having said all that ... the only reason to have num_oubput_obs_members equal to the ensemble size is to provide the option to calculate the rank histogram. However, the additional amount of memory required to hold the full ensemble of expected observations is miniscule relative to the amount needed as a whole. If you are that close to memory limit, I can almost guarantee that you will have transient problems when you happen to get dispatched on nodes that (for whatever reason) do not have all the memory availble.

Now ... about the NE peak ... The  EnKF algorithms are designed for gaussian variables, and do not make any attempt to preserve variables to physical limits or preserve mass or energy or ... BUT DART recognizes that some variables have limits and has the capability to truncate (not a great option, but there it is) the posterior state of the variables when updating the model restart file. Please note that the DART diagnostic files will not be truncated. This gives you some idea of where the DA wants to push the state, but by truncating the variables in the model restart file, you may be able to avoid unphysical values that could cause the model to blow up. The truncation values are specified in the model_nml namelist, by the variable 'variables' in the third and fourth column:

```
&model_nml
   debug                       = 2
   tiegcm_restart_file_name    = 'tiegcm_restart_p.nc'
   tiegcm_secondary_file_name  = 'tiegcm_s.nc'
   tiegcm_namelist_file_name   = 'tiegcm.nml'
   assimilation_period_seconds = 172800
   estimate_f10_7              = .false.
   variables = 'NE',    'KIND_ELECTRON_DENSITY',           '1000.0',  '1.0e20',  'restart',    'UPDATE'
   ...
```

I'm trying to understand more of what you mean by _"...pathological states without an NE peak?"_
In one of the ensemble members without a peak in NE, what do the DART (prior and posterior) files look like?
Do they seem sensible?  Since this version of DART has a 'dart_to_model.f90' component, you could implement some sort of vertical consistency for NE, but this is not currently part of the program.

**Pull request merged**
